from Bio import SeqIO
from Bio.Seq import Seq
import pandas as pd

class log:
    """
    Simple class to print texts in color
    """

    f = lambda color: lambda string: print(color + string + "\33[0m")

    black = f("\33[30m")
    red = f("\33[31m")
    green = f("\33[32m")
    yellow = f("\33[33m")
    blue = f("\33[34m")
    magenta = f("\33[35m")
    cyan = f("\33[36m")
    white = f("\33[37m")

def visualize_seq(target_fasta, res_table):
    """
    simple visualization of target and probe sequences
    Parameters
    ----------
    target_fasta: str
        Path to FASTA file
    res_table: pd.DataFrame
        pandas DataFrame generated by oligodesigner.generator
    """
    target = SeqIO.read(target_fasta, "fasta")
    
    out1 = [" "] * len(target)
    out2 = [" "] * len(target)
    for i, row in res_table.iterrows():
        out1[int(row["start"]-1):int(row["end"]-1)] = str(row["seq"][::-1])
        out2[int(row["start"]-1):int(row["start"]-1+3)] = f"{i:03d}" 
    
    for i in range(0, len(target), 50):
        log.green("             ID: " + "".join(out2[i:i+50]))
        log.blue(" Probe (3'->5'): " + "".join(out1[i:i+50]))
        log.black("Target (5'->3'): " + target.seq[i:i+50] + " " + str(i+50))

def export_opool_spreadsheet(poolname, res_table, savename):
    """
    export oligo probe sequences in IDT's oPool submission format in Excel.
    Parameters
    ----------
    poolname: str
        "Pool name" column of the IDT's oPool submission
    res_table: pd.DataFrame
        pandas DataFrame generated by oligodesigner.generator
    savename: str
        Output file name, should end with ".xlsx" extension
    """
    df = pd.DataFrame(columns=["Pool name", "Sequence"])
    seqs = res_table["hcr_seq"].tolist()
    seqs = [str(s) for s in seqs]
    df["Sequence"] = seqs
    df["Pool name"] = poolname
    df.to_excel(savename, index=False)
    print("Spreadsheet saved as", savename)
